services:
  - type: web
    name: ml-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api_ml.py"
    envVars:
      - key: PORT
        value: 5000
    runtime: python-3.10.13
