services:
  - type: web
    name: ml-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_ml:app"
    pythonVersion: "3.10"
    envVars:
      - key: PORT
        value: 5000
